#!/bin/sh

INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`

if [ "$START_LINE" =  "#Validate" ]; then
    if [ -e .commit ]; then
        echo "Start lint test..."
        pylint -rn --rcfile pylintrc src/*.py validator/*.py
        retVal=$?

        if [ $retVal -ne 0 ]; then
            echo "pylint test failed failed."
            exit 1
        fi

        echo "Start validation..."
        python3 validator/run.py
        retVal=$?
        if [ $retVal -ne 0 ]; then
            echo "Validation failed."
            exit 1
        fi
        git add validator_results.json
    fi
fi
